#!/usr/bin/python

import os
from concurrent import futures 

# pacman -S libheif
command = 'heif-convert -q 100 {} {}.jpeg'

def convert(filename):
    print(f'Convert {filename}')
    fname, _ = filename.split('.')
    os.system(command.format(filename, fname))
    os.remove(filename)


files = [f for f in os.listdir('.') if f.endswith('.HEIC')]
with futures.ProcessPoolExecutor() as executor:
    futures = executor.map(convert, files)

# Remove depth files
for f in os.listdir('.'):
    if 'depth' in f:
        os.remove(f)
