author = 'Rayhan Kafi Pratama (@rxyhn)'
description = 'Awesome desktop with floating panels'
credits = 'https://github.com/rxyhn/dotfiles'
dependencies = [
	'awesome-git',
	'picom',
	'rofi',
	'alacritty',
	'brightnessctl',
	'pulseaudio',
	'mpd',
	'mpc',
	'mpdris2',
	'ncmpcpp',
	'playerctl',
	'lm-sensors',
	'xclip'
]
