#!/bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

# •• Wallpaper
~/.fehbg

# •• Polybar
~/.config/polybar/launch.sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Zathura state=tiled

# •• Colors
bspc config normal_border_color "#ee00ff"
bspc config active_border_color "#38369C"
bspc config focused_border_color "#00FFFF"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true
bspc config bottom_padding 30
bspc config top_padding 90
bspc config left_padding 40
bspc config right_padding 40

# •• Keymap
setxkbmap -layout us -variant altgr-intl

# •• Compositor
picom --experimental-backends &

# •• Key press rate
xset r rate 200 40
