#!/bin/node

const fs = require('fs')
const { exec } = require("child_process");

exec("ls /sys/class/backlight", (error, stdout, stderr) => {
	if ( error ) return
	if ( stderr ) console.error(stderr)

	let device = stdout.trim()

	brightnessFile = `/sys/class/backlight/${device}/brightness`;
	maxBrightnessFile = `/sys/class/backlight/${device}/max_brightness`;

	maxValue = parseInt(fs.readFileSync(maxBrightnessFile, 'utf8'));

	fs.watch(brightnessFile, () => {
		value = parseInt(fs.readFileSync(brightnessFile, 'utf8'));
		console.log(Math.round(value / maxValue * 100));
	})
})
