author="David Rodríguez (@daavidrgz)"
description="desktop"
credits="https://github.com/jollycampio/dotfiles"
dependencies=[
	"paperview (https://github.com/glouw/paperview)",
	"bspwm",
	"sxhkd",
	"rofi",
	"polybar",
	"dunst",
	"pulseaudio",
	"pamixer",
	"feh",
	"dunstify",
	"brightnessctl",
	"playerctl",
	"mpd",
	"newsboat (Optional)",
	"mpd-notification (Optional)",
	"flameshot (Optional)",
	"alacritty (Optional)",
	"better-discord (Optional)",
	"spicetify (Optional)",
]
