#!/bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝

# •• Wallpaper
~/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config pointer_motion_interval 5

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X

bspc config window_gap 20
bspc config border_width 0
bspc config border_radius 14

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Zathura state=tiled
bspc rule -a Rofi state=floating

# •• Keymap
setxkbmap -layout us -variant altgr-intl

# •• Key press rate
xset r rate 200 40

# •• Apps
picom --experimental-backends &

$HOME/.config/xob/xob-start &
$HOME/.config/tint2/tint2-start &
udiskie &

