complete -c gtheme -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c gtheme -n "__fish_use_subcommand" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_use_subcommand" -f -a "theme" -d 'Manage themes'
complete -c gtheme -n "__fish_use_subcommand" -f -a "desktop" -d 'Manage desktops'
complete -c gtheme -n "__fish_use_subcommand" -f -a "pattern" -d 'Manage patterns'
complete -c gtheme -n "__fish_use_subcommand" -f -a "extra" -d 'Manage extras'
complete -c gtheme -n "__fish_use_subcommand" -f -a "fav" -d 'Manage fav themes'
complete -c gtheme -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from apply; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from apply; and not __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from apply; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all installed themes'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from apply; and not __fish_seen_subcommand_from help" -f -a "apply" -d 'Apply specified theme'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from apply; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from list" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from apply" -s p -l pattern -d 'Apply the theme only on selected patterns' -r
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from apply" -s i -l invert -d 'Invert the foreground and background colors on selected patterns' -r
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from apply" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from apply" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from apply" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from help" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all installed desktops'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install specified desktop'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from list" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from install" -s t -l theme -d 'Apply specified theme after installing the desktop' -r
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from install" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from install" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from help" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from desktop; and __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from invert; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from invert; and not __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from invert; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List all patterns of the current desktop by default'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from invert; and not __fish_seen_subcommand_from help" -f -a "enable" -d 'Enable specified patterns in the current desktop'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from invert; and not __fish_seen_subcommand_from help" -f -a "disable" -d 'Disable specified patterns in the current desktop'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from invert; and not __fish_seen_subcommand_from help" -f -a "toggle" -d 'Toggle specified patterns in the current desktop'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from invert; and not __fish_seen_subcommand_from help" -f -a "invert" -d 'Invert specified patterns or return them to default if they are already inverted'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from invert; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from list" -s d -l desktop -d 'List patterns of the specified desktop' -r
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from list" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from enable" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from enable" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from enable" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from disable" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from disable" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from disable" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from toggle" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from toggle" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from toggle" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from invert" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from invert" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from invert" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from help" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from pattern; and __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "enable" -d 'Enable specified extras in the current desktop'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "disable" -d 'Disable specified extras in the current desktop'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "toggle" -d 'Toggle specified extras in the current desktop'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and not __fish_seen_subcommand_from enable; and not __fish_seen_subcommand_from disable; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from enable" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from enable" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from enable" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from disable" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from disable" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from disable" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from toggle" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from toggle" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from toggle" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from help" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from extra; and __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List favourite themes'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "add" -d 'Add selected themes to the favourite themes list'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove selected themes from the favourite themes list'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "toggle" -d 'Toggle selected themes from the favourite themes list'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from toggle; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from list" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from add" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from add" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from remove" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from remove" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from toggle" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from toggle" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from toggle" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from help" -l version -d 'Print version information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c gtheme -n "__fish_seen_subcommand_from fav; and __fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
complete -c gtheme -n "__fish_seen_subcommand_from help" -s v -l verbose -d 'Show more information'
