author="David Rodríguez (@daavidrgz)"
description="desktop"
credits="https://github.com/mdnght-4/dotfiles"
dependencies=[
	"https://github.com/wmutils/opt (Tool to have double borders)",
	"bspwm",
	"sxhkd",
	"picom",
	"rofi",
	"polybar",
	"dunst",
	"pulseaudio",
	"pamixer",
	"feh",
	"brightnessctl",
	"playerctl",
	"flameshot (Optional)",
	"alacritty (Optional)",
	"better-discord (Optional)",
	"spicetify (Optional)",
]
